#################################################
# Server
#################################################
server.port=8080

#################################################
# Application
#################################################
spring.application.name=Neighborhood Event Management System

#################################################
# Database
#################################################
spring.datasource.url=jdbc:mysql://localhost:3306/neighborhood_events
spring.datasource.username=root
spring.datasource.password=SarathaDelfina@13
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#################################################
# JPA / Hibernate
#################################################
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

#################################################
# JWT
#################################################
app.jwtSecret=neighborhood-secret-key-2026-neighborhood-event-management-system
app.jwtExpirationInMs=86400000

#################################################
# Mail
#################################################
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sarathaakash13@gmail.com
spring.mail.password=ejus omzd ulds uoeu

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

#################################################
# Logging
#################################################

logging.level.org.springframework.security=DEBUG
logging.level.com.neighborhood.eventmanagement=DEBUG

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

springdoc.swagger-ui.path=/swagger-ui.html

springdoc.api-docs.path=/api-docs